version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "Rust"
    assignees:
      - "46ki75"
    reviewers:
      - "46ki75"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "npm"
    assignees:
      - "46ki75"
    reviewers:
      - "46ki75"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    target-branch: "develop"
    labels:
      - "Terraform"
    assignees:
      - "46ki75"
    reviewers:
      - "46ki75"
