version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "46ki75"
    reviewers:
      - "46ki75"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "46ki75"
    reviewers:
      - "46ki75"
