name: Test

on:
  push:
    paths-ignore:
      - docs
  pull_request:
    paths-ignore:
      - docs
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  notionrs:
    name: Unit Test (notionrs_types)
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Unit Test
        run: cargo test --lib
        working-directory: ./notionrs_types

  notionrs-macro-unit:
    name: Unit Test (notionrs_macro)
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Unit Test
        run: cargo test --lib
        working-directory: ./notionrs_macro

  notionrs-macro-integration:
    name: Integration Test (notionrs_macro)
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Unit Test
        run: cargo test
        working-directory: ./notionrs_macro
