name: Unit Test

on:
  push:
    paths-ignore:
      - docs
  pull_request:
    paths-ignore:
      - docs
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  notionrs:
    name: Unit Test (notionrs)
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Unit Test
        run: cargo test --lib
        working-directory: ./notionrs

  notionrs-macro:
    name: Unit Test (notionrs-macro)
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Unit Test
        run: cargo test --lib
        working-directory: ./notionrs-macro
